stages:
  - test
  - release

lint:
  stage: test
  image: registry.gitlab.com/etke.cc/base/build
  script:
    - make lint

unit:
  stage: test
  image: registry.gitlab.com/etke.cc/base/build
  script:
    - make test

docker:
  stage: release
  only: ['main', 'tags']
  services:
    - docker:dind
  image: jdrouet/docker-with-buildx:stable
  before_script:
    - apk --no-cache add make
  script:
    - make login docker
  tags:
    - docker
